# Generated by Django 6.0.3 on 2026-03-17 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('company_name', models.CharField(blank=True, default='', max_length=200)),
                ('current_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('change', models.DecimalField(decimal_places=4, help_text='Price change', max_digits=12)),
                ('change_percent', models.DecimalField(decimal_places=4, help_text='Change %', max_digits=8)),
                ('day_high', models.DecimalField(decimal_places=4, max_digits=12)),
                ('day_low', models.DecimalField(decimal_places=4, max_digits=12)),
                ('open_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('previous_close', models.DecimalField(decimal_places=4, max_digits=12)),
                ('timestamp', models.DateTimeField(help_text='Quote timestamp from Finnhub')),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stock Quote',
                'verbose_name_plural': 'Stock Quotes',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='WeatherCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_key', models.CharField(help_text="'lat,lon' string, e.g. '40.71,-74.01'", max_length=50, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('temperature', models.FloatField(help_text='Current temperature')),
                ('temperature_unit', models.CharField(default='fahrenheit', max_length=10)),
                ('feels_like', models.FloatField(blank=True, null=True)),
                ('humidity', models.IntegerField(blank=True, help_text='Relative humidity %', null=True)),
                ('wind_speed', models.FloatField(blank=True, null=True)),
                ('wind_direction', models.IntegerField(blank=True, help_text='Degrees', null=True)),
                ('weather_code', models.IntegerField(help_text='WMO weather interpretation code (0=clear, 1-3=cloudy, etc.)')),
                ('precipitation_probability', models.IntegerField(blank=True, null=True)),
                ('sunrise', models.TimeField(blank=True, null=True)),
                ('sunset', models.TimeField(blank=True, null=True)),
                ('hourly_forecast', models.JSONField(default=list, help_text='List of hourly data: [{time, temp, weather_code, precip_prob}, ...]')),
                ('daily_high', models.FloatField(blank=True, null=True)),
                ('daily_low', models.FloatField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Weather Cache',
                'verbose_name_plural': 'Weather Cache',
            },
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(help_text='ICS feed URL this event came from')),
                ('uid', models.CharField(help_text='iCal UID for deduplication', max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', max_length=500)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('all_day', models.BooleanField(default=False)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Calendar Event',
                'verbose_name_plural': 'Calendar Events',
                'ordering': ['start'],
                'unique_together': {('source_url', 'uid')},
            },
        ),
        migrations.CreateModel(
            name='NewsHeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(help_text='RSS feed URL this headline came from')),
                ('source_name', models.CharField(blank=True, default='', help_text="Display name for the source (e.g., 'BBC News')", max_length=200)),
                ('guid', models.CharField(help_text='RSS item guid/id for deduplication', max_length=500)),
                ('title', models.CharField(max_length=1000)),
                ('link', models.URLField(blank=True, default='', max_length=2000)),
                ('summary', models.TextField(blank=True, default='')),
                ('published_at', models.DateTimeField(blank=True, help_text='Publication timestamp from the RSS feed', null=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'News Headline',
                'verbose_name_plural': 'News Headlines',
                'ordering': ['-published_at'],
                'unique_together': {('source_url', 'guid')},
            },
        ),
        migrations.CreateModel(
            name='UserDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_layout', models.JSONField(default=list, help_text='Ordered list of widget configs: [{widget, enabled, position, settings}, ...]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Dashboard',
                'verbose_name_plural': 'User Dashboards',
            },
        ),
    ]
