# Generated by Django 5.2.12 on 2026-03-30 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlucoseReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(help_text='Blood glucose in mg/dL')),
                ('mmol_l', models.DecimalField(decimal_places=1, help_text='Blood glucose in mmol/L', max_digits=4)),
                ('trend_direction', models.CharField(help_text='e.g. Flat, FortyFiveUp, SingleUp', max_length=30)),
                ('trend_arrow', models.CharField(help_text='Unicode trend arrow', max_length=5)),
                ('recorded_at', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glucose_readings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Glucose Reading',
                'verbose_name_plural': 'Glucose Readings',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['user', '-recorded_at'], name='dashboard_g_user_id_f77971_idx')],
            },
        ),
    ]
