# Generated by Django 5.2.12 on 2026-04-01 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_glucosereading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='source_url',
            field=models.URLField(help_text="Event source identifier (e.g. 'google:1')"),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(help_text='Event UID for deduplication', max_length=255),
        ),
    ]
