# Generated by Django 5.2.12 on 2026-04-22 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_calendarevent_source_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', help_text="Optional label, e.g. 'pasta'", max_length=100)),
                ('duration_seconds', models.PositiveIntegerField(help_text='Original duration in seconds')),
                ('expires_at', models.DateTimeField(help_text='When the timer goes off')),
                ('status', models.CharField(choices=[('running', 'Running'), ('ringing', 'Ringing'), ('cancelled', 'Cancelled'), ('dismissed', 'Dismissed')], default='running', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Timer',
                'verbose_name_plural': 'Timers',
                'ordering': ['expires_at'],
            },
        ),
    ]
